name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Instalando dependencias'
        run: npm ci 

      - name: 'Instalando cypress'
        run: npm install cypress --save-dev

      - name: 'Test E2E'
        run: npm run e2e